/**
 * Camera setting variation prompts for image generation
 * Includes diverse camera angles, movements, and B-roll footage options
 * Ordered to provide maximum variety in perspective and style
 */
export const CAMERA_VARIATIONS = [
  "AMERICAN SHOT — FRAMING FROM KNEES UP; versatile composition showing body language while maintaining facial detail.",
  "ANAMORPHIC FLARE — HORIZONTAL LENS FLARES and bokeh; creates cinematic premium look with characteristic oval bokeh.",
  "B-ROLL: ATMOSPHERIC ELEMENTS — CAPTURE of light rays, dust particles, steam, or weather effects; adds mood and cinematic quality.",
  "B-ROLL: ENVIRONMENTAL TEXTURE — DETAIL SHOT of surfaces, materials, or patterns in scene; establishes atmosphere and production value.",
  "B-ROLL: ESTABLISHING WIDE — EXPANSIVE SHOT showing location and context; orients viewer to space before closer shots.",
  "B-ROLL: HANDS IN ACTION — CLOSE-UP of hands performing task or gesture; adds human element and narrative detail.",
  "B-ROLL: TRANSITION ELEMENT — ABSTRACT MOVEMENT or color that serves as visual bridge; smooth cuts between main footage.",
  "BOKEH FOREGROUND — EXTREME SHALLOW DEPTH with out-of-focus elements in front; creates dreamy separation and visual interest.",
  "BULLET TIME FREEZE — 360-DEGREE ARRAY with frozen moment; creates matrix-style suspended-time effect with rotating perspective.",
  "CANTED HORIZON EXTREME — CAMERA TILTED 60-90 DEGREES; creates surreal, disorienting perspective for dramatic effect.",
  "CINEMATIC TELEPHOTO COMPRESSION — LONG LENS, SHALLOW DEPTH; subject isolated with beautifully blurred foreground and background.",
  "COWBOY SHOT — FRAMING FROM MID-THIGH UP; classic western composition balancing character and environment.",
  "CRAB WALK LATERAL — CAMERA MOVES SIDEWAYS perpendicular to subject; reveals parallel action or environment details.",
  "CRANE SHOT ASCENDING — CAMERA RISES SMOOTHLY from ground level to elevated view; reveals scale and context progressively.",
  "CRASH PUSH-IN — AGGRESSIVE RAPID DOLLY toward subject; creates urgency, shock, or comedic punctuation.",
  "CRASH ZOOM OUT — RAPID ZOOM AWAY from subject; creates jarring reveal of wider context or comedic effect.",
  "DOLLY ZOOM VERTIGO — CAMERA PULLS BACK while zooming in; creates disorienting perspective shift that emphasizes emotional moment.",
  "DRONE AERIAL DESCENT — CAMERA DESCENDS FROM HIGH ALTITUDE toward subject; reveals environment scale before intimate framing.",
  "DRONE FLYOVER SWEEP — LOW-ALTITUDE PASS over landscape or subject; creates immersive sense of speed and spatial relationship.",
  "DRONE ORBITAL RISE — CIRCULAR MOVEMENT while ascending; combines rotation with elevation for dynamic reveal.",
  "DRONE TOP-DOWN TRACKING — BIRD'S EYE VIEW following subject movement; creates abstract patterns and emphasizes path or journey.",
  "DUTCH ANGLE DYNAMIC — CAMERA TILTED 25-45 DEGREES; creates tension and energy while maintaining subject clarity.",
  "EXTREME LOW‑ANGLE HERO — CAMERA JUST ABOVE GROUND, TILTED UP; architecture looms while SILHOUETTE STAYS READABLE.",
  "FISH-EYE DISTORTION — ULTRA-WIDE LENS with spherical distortion; creates surreal, exaggerated perspective and spatial warping.",
  "GIMBAL CHASE — DYNAMIC FOLLOWING SHOT with stabilized movement; maintains smooth framing during fast-paced action.",
  "GOLDEN HOUR BACKLIGHTING — SUBJECT ILLUMINATED FROM BEHIND with warm rim lighting; creates atmospheric depth with glowing edges and soft shadows.",
  "HANDHELD INTIMATE — SUBTLE CAMERA SHAKE with close framing; creates documentary-style authenticity and immediacy.",
  "INFRARED THERMAL — HEAT-SIGNATURE VISUAL STYLE; creates otherworldly aesthetic with false color temperature mapping.",
  "JIB ARM SWEEP — SMOOTH ARCING MOVEMENT on extended arm; combines horizontal and vertical motion for elegant reveals.",
  "KALEIDOSCOPE MIRROR — SYMMETRICAL REFLECTION creating geometric patterns; transforms reality into abstract visual design.",
  "LOCKED-OFF STATIC — COMPLETELY STILL CAMERA on tripod; creates formal, composed frame emphasizing subject movement.",
  "MACRO DETAIL SHOT — EXTREME CLOSE-UP of texture or small object; reveals intricate details invisible to naked eye.",
  "ORBITAL ROTATION — CAMERA CIRCLES AROUND SUBJECT at consistent distance; showcases subject from all angles while maintaining focus.",
  "OVER-THE-SHOULDER — CAMERA BEHIND ONE SUBJECT looking at another; establishes conversation dynamics and point of view.",
  "OVERHEAD BIRD'S EYE VIEW — CAMERA DIRECTLY ABOVE looking down; flattens perspective and creates geometric patterns.",
  "PERISCOPE SHOT — LOW-ANGLE CAMERA peering over obstacle or through gap; creates voyeuristic or hidden perspective.",
  "POV FIRST-PERSON — CAMERA AS CHARACTER'S EYES; creates immersive subjective experience and emotional connection.",
  "PRISMATIC SPLIT — MULTIPLE OVERLAPPING IMAGES from single lens; creates fragmented, artistic interpretation of scene.",
  "PROFILE EXTREME CLOSE‑UP — NOSE‑LIP‑CHIN CONTOUR in relief; single kicker light sculpts the edge.",
  "PULL-OUT REVEAL — CAMERA MOVES BACKWARD to reveal wider context; creates surprise by showing previously hidden information.",
  "PUSH-IN SLOW — GRADUAL CAMERA MOVEMENT toward subject; builds tension and draws viewer's attention to specific detail.",
  "RACK FOCUS SHIFT — FOCUS TRANSITIONS from foreground to background or vice versa; directs attention and reveals narrative layers.",
  "REFLECTION SHOT — SUBJECT CAPTURED IN MIRROR, WATER, or glass surface; adds visual depth and symbolic layering.",
  "REVERSE ANGLE — CAMERA POSITIONED 180 DEGREES from previous shot; shows opposite perspective and spatial relationships.",
  "SILHOUETTE CONTRE-JOUR — SUBJECT BACKLIT INTO DARK SHAPE against bright background; emphasizes form and creates dramatic contrast.",
  "SLIDER LATERAL MOVE — HORIZONTAL CAMERA GLIDE parallel to subject; adds subtle production value and dimensional depth.",
  "SNORRICAM POV — CAMERA MOUNTED TO SUBJECT facing them; creates intense subjective perspective with moving background.",
  "SPIRAL DESCENT — CAMERA ROTATES while descending around subject; combines orbital and crane movements for complex reveal.",
  "SPLIT DIOPTER FOCUS — TWO FOCAL PLANES IN SHARP FOCUS simultaneously; foreground and background both clear despite distance.",
  "STEADICAM FLOWING — SMOOTH GLIDING MOVEMENT through space; elegant navigation around obstacles with fluid motion.",
  "THROUGH-FRAME COMPOSITION — CAMERA SHOOTS THROUGH FOREGROUND ELEMENT like doorway, window, or foliage; creates natural framing and depth.",
  "TILT DOWN DISCOVERY — CAMERA STARTS HIGH and tilts downward; creates anticipation before revealing ground-level detail.",
  "TILT UP REVEAL — CAMERA STARTS LOW and tilts upward; progressively reveals subject height or grandeur.",
  "TILT-SHIFT MINIATURE — SELECTIVE FOCUS creating toy-like effect; transforms real scenes into surreal miniature appearance.",
  "TIME-LAPSE COMPRESSION — ACCELERATED PASSAGE OF TIME; reveals slow changes like shadows, crowds, or natural phenomena.",
  "TRACKING SHOT PARALLEL — CAMERA MOVES ALONGSIDE SUBJECT at matching speed; maintains consistent framing while revealing environment.",
  "ULTRA-WIDE ESTABLISHING — EXPANSIVE FIELD OF VIEW capturing entire scene; emphasizes scale and environmental context.",
  "WHIP PAN TRANSITION — RAPID HORIZONTAL CAMERA MOVEMENT with motion blur; creates energetic connection between scenes.",
  "WHIP TILT VERTICAL — RAPID VERTICAL CAMERA MOVEMENT with motion blur; energetic transition between vertical elements.",
  "WIDE SHOT TWO-SHOT — MEDIUM-WIDE FRAMING of two subjects in space; shows interaction and spatial relationship clearly.",
  "WIDE-ANGLE ENVIRONMENTAL SHOT — SUBJECT IN CONTEXT with surrounding space; captures relationship between subject and environment with expansive field of view.",
  "WORM'S EYE ULTRA-WIDE — EXTREME LOW ANGLE with wide lens; dramatic distortion emphasizes height and power.",
  "ZOOM-IN PUNCH — RAPID ZOOM toward subject or detail; creates emphasis and urgency without camera movement.",
] as const;
