/**
 * Camera setting variation prompts for image generation.
 *
 * Includes diverse camera angles, movements, and cinematography techniques.
 * Ordered to provide maximum variety in perspective and style.
 *
 * Note: B-roll variations are now generated dynamically via AI based on
 * image analysis rather than using predefined templates.
 */
export const CAMERA_VARIATIONS = [
  "AMERICAN SHOT — FRAMING FROM KNEES UP; versatile composition showing body language while maintaining facial detail.",
  "ANAMORPHIC FLARE — HORIZONTAL LENS FLARES and bokeh; creates cinematic premium look with characteristic oval bokeh.",
  "B-ROLL: ATMOSPHERIC ELEMENTS — CAPTURE of light rays, dust particles, steam, or weather effects; adds mood and cinematic quality.",
  "B-ROLL: ENVIRONMENTAL TEXTURE — DETAIL SHOT of surfaces, materials, or patterns in scene; establishes atmosphere and production value.",
  "B-ROLL: ESTABLISHING WIDE — EXPANSIVE SHOT showing location and context; orients viewer to space before closer shots.",
  "B-ROLL: HANDS IN ACTION — CLOSE-UP of hands performing task or gesture; adds human element and narrative detail.",
  "B-ROLL: TRANSITION ELEMENT — ABSTRACT MOVEMENT or color that serves as visual bridge; smooth cuts between main footage.",
  "BULLET TIME FREEZE — 360-DEGREE ARRAY with frozen moment; creates matrix-style suspended-time effect with rotating perspective.",
  "CANTED HORIZON EXTREME — CAMERA TILTED 60-90 DEGREES; creates surreal, disorienting perspective for dramatic effect.",
  "CINEMATIC TELEPHOTO COMPRESSION — LONG LENS, SHALLOW DEPTH; subject isolated with beautifully blurred foreground and background.",
  "COWBOY SHOT — FRAMING FROM MID-THIGH UP; classic western composition balancing character and environment.",
  "CRAB WALK LATERAL — CAMERA MOVES SIDEWAYS perpendicular to subject; reveals parallel action or environment details.",
  "CRASH PUSH-IN — AGGRESSIVE RAPID DOLLY toward subject; creates urgency, shock, or comedic punctuation.",
  "CRASH ZOOM OUT — RAPID ZOOM AWAY from subject; creates jarring reveal of wider context or comedic effect.",
  "CROWD ISOLATION — TELEPHOTO LENS with shallow depth of field; sharp focus on single subject while blurring surrounding crowd into abstract shapes.",
  "DOLLY ZOOM VERTIGO — CAMERA PULLS BACK while zooming in; creates disorienting perspective shift that emphasizes emotional moment.",
  "DOUBLE EXPOSURE LAYER — TWO IMAGES SUPERIMPOSED; creates ghost-like blending of subject and environment or two distinct concepts.",
  "DUTCH ANGLE DYNAMIC — CAMERA TILTED 25-45 DEGREES; creates tension and energy while maintaining subject clarity.",
  "EXTREME LOW‑ANGLE HERO — CAMERA JUST ABOVE GROUND, TILTED UP; architecture looms while SILHOUETTE STAYS READABLE.",
  "FISH-EYE DISTORTION — ULTRA-WIDE LENS with spherical distortion; creates surreal, exaggerated perspective and spatial warping.",
  "FOURTH WALL BREAK — SUBJECT LOOKING DIRECTLY into lens; establishes direct connection and acknowledgment of the viewer.",
  "GIMBAL CHASE — DYNAMIC FOLLOWING SHOT with stabilized movement; maintains smooth framing during fast-paced action.",
  "GOLDEN HOUR BACKLIGHTING — SUBJECT ILLUMINATED FROM BEHIND with warm rim lighting; creates atmospheric depth with glowing edges and soft shadows.",
  "INFRARED DREAMSCAPE — SURREAL COLOR SHIFT to pinks and whites; transforms foliage and skin tones into otherworldly dream palette.",
  "ISOMETRIC STUDIO SHOT — HIGH-ANGLE ORTHOGRAPHIC VIEW with parallel projection; creates clean, geometric, stylized look with evenly distributed lighting.",
  "JIB ARM SWEEP — SMOOTH ARCING MOVEMENT on extended arm; combines horizontal and vertical motion for elegant reveals.",
  "LOCKED-OFF STATIC — COMPLETELY STILL CAMERA on tripod; creates formal, composed frame emphasizing subject movement.",
  "MACRO DETAIL SHOT — EXTREME CLOSE-UP of texture or small object; reveals intricate details invisible to naked eye.",
  "ORBITAL ROTATION — CAMERA CIRCLES AROUND SUBJECT at consistent distance; showcases subject from all angles while maintaining focus.",
  "OVER-THE-SHOULDER — CAMERA BEHIND ONE SUBJECT looking at another; establishes conversation dynamics and point of view.",
  "OVERHEAD BIRD'S EYE VIEW — CAMERA DIRECTLY ABOVE looking down; flattens perspective and creates geometric patterns.",
  "PERISCOPE SHOT — LOW-ANGLE CAMERA peering over obstacle or through gap; creates voyeuristic or hidden perspective.",
  "POV FIRST-PERSON — CAMERA AS CHARACTER'S EYES; creates immersive subjective experience and emotional connection.",
  "PROFILE EXTREME CLOSE‑UP — NOSE‑LIP‑CHIN CONTOUR in relief; single kicker light sculpts the edge.",
  "PULL-OUT REVEAL — CAMERA MOVES BACKWARD to reveal wider context; creates surprise by showing previously hidden information.",
  "PUSH-IN SLOW — GRADUAL CAMERA MOVEMENT toward subject; builds tension and draws viewer's attention to specific detail.",
  "RACK FOCUS SHIFT — FOCUS TRANSITIONS from foreground to background or vice versa; directs attention and reveals narrative layers.",
  "REFLECTION SHOT — SUBJECT CAPTURED IN MIRROR, WATER, or glass surface; adds visual depth and symbolic layering.",
  "REVERSE ANGLE — CAMERA POSITIONED 180 DEGREES from previous shot; shows opposite perspective and spatial relationships.",
  "SILHOUETTE CONTRE-JOUR — SUBJECT BACKLIT INTO DARK SHAPE against bright background; emphasizes form and creates dramatic contrast.",
  "SLIDER LATERAL MOVE — HORIZONTAL CAMERA GLIDE parallel to subject; adds subtle production value and dimensional depth.",
  "SNORRICAM BODY MOUNT — CAMERA RIGGED TO ACTOR'S BODY facing face; background moves violently while subject remains locked in center frame.",
  "SPIRAL DESCENT — CAMERA ROTATES while descending around subject; combines orbital and crane movements for complex reveal.",
  "SPLIT DIOPTER FOCUS — TWO FOCAL PLANES IN SHARP FOCUS simultaneously; foreground and background both clear despite distance.",
  "STEADICAM FLOWING — SMOOTH GLIDING MOVEMENT through space; elegant navigation around obstacles with fluid motion.",
  "STORY END: FADE OUT — WIDE SHOT WALKING AWAY into distance; diminishing subject size with gradual darkening or sunset lighting for closure.",
  "STORY START: AWAKENING — POV BLURRY TO SHARP transition effect; captures the moment of waking up with soft morning light and adjusting focus.",
  "THROUGH-FRAME COMPOSITION — CAMERA SHOOTS THROUGH FOREGROUND ELEMENT like doorway, window, or foliage; creates natural framing and depth.",
  "TILT DOWN DISCOVERY — CAMERA STARTS HIGH and tilts downward; creates anticipation before revealing ground-level detail.",
  "TILT UP REVEAL — CAMERA STARTS LOW and tilts upward; progressively reveals subject height or grandeur.",
  "TILT-SHIFT MINIATURE — SELECTIVE FOCUS creating toy-like effect; transforms real scenes into surreal miniature appearance.",
  "TIME-LAPSE COMPRESSION — ACCELERATED PASSAGE OF TIME; reveals slow changes like shadows, crowds, or natural phenomena.",
  "TRACKING SHOT PARALLEL — CAMERA MOVES ALONGSIDE SUBJECT at matching speed; maintains consistent framing while revealing environment.",
  "ULTRA-WIDE ESTABLISHING — EXPANSIVE FIELD OF VIEW capturing entire scene; emphasizes scale and environmental context.",
  "UNDERWATER SUBMERSION — PARTIAL OR FULL UNDERWATER view; captures distorted light refraction, bubbles, and floating weightlessness.",
  "WHIP PAN TRANSITION — RAPID HORIZONTAL CAMERA MOVEMENT with motion blur; creates energetic connection between scenes.",
  "WHIP TILT VERTICAL — RAPID VERTICAL CAMERA MOVEMENT with motion blur; energetic transition between vertical elements.",
  "WIDE SHOT TWO-SHOT — MEDIUM-WIDE FRAMING of two subjects in space; shows interaction and spatial relationship clearly.",
  "WIDE-ANGLE ENVIRONMENTAL SHOT — SUBJECT IN CONTEXT with surrounding space; captures relationship between subject and environment with expansive field of view.",
  "WORM'S EYE ULTRA-WIDE — EXTREME LOW ANGLE with wide lens; dramatic distortion emphasizes height and power.",
  "ZOOM-IN PUNCH — RAPID ZOOM toward subject or detail; creates emphasis and urgency without camera movement.",
] as const;
