export const EMOTION_VARIATIONS = [
  "Amusement",
  "Anger",
  "Anticipation",
  "Anxiety",
  "Awe",
  "Boredom",
  "Confidence",
  "Confusion",
  "Curiosity",
  "Despair",
  "Determination",
  "Disgust",
  "Envy",
  "Excitement",
  "Exhaustion",
  "Fear",
  "Gratitude",
  "Guilt",
  "Hope",
  "Joy",
  "Loneliness",
  "Melancholy",
  "Mystery",
  "Nostalgia",
  "Pride",
  "Rage",
  "Relief",
  "Romance",
  "Sadness",
  "Satisfaction",
  "Serenity",
  "Shame",
  "Surprise",
  "Tension",
  "Trust",
] as const;

export type EmotionVariation = (typeof EMOTION_VARIATIONS)[number];
