/**
 * Lighting variation prompts for image generation.
 *
 * Includes diverse lighting scenarios, from natural light to studio setups,
 * creative lighting effects, and atmospheric conditions.
 * Ordered to provide maximum variety in mood, direction, and quality.
 */
export const LIGHTING_VARIATIONS = [
  "ATMOSPHERIC HAZE — LIGHT SCATTER through particles; adds depth, mystery, and cinematic atmosphere.",
  "BACKLIT SILHOUETTE — STRONG LIGHT BEHIND SUBJECT creating dark outline; emphasizes shape and form with minimal detail.",
  "BEAUTY DISH — WRAPPED LIGHT with soft shadows; creates flattering portrait lighting with catch lights.",
  "BLUE HOUR COOL — TWILIGHT AMBIENT LIGHT with deep blue tones; adds mysterious, serene mood with cool color temperature.",
  "BOUNCE LIGHT — LIGHT REFLECTED off surface; creates soft, indirect, natural-looking fill.",
  "BUTTERFLY LIGHTING — LIGHT DIRECTLY ABOVE casting shadow under nose; glamorous beauty lighting with symmetrical shadows.",
  "CHIAROSCURO — EXTREME LIGHT-DARK CONTRAST with selective illumination; creates Renaissance painting quality.",
  "COLD MOONLIGHT — BLUE-TINTED NIGHT ILLUMINATION; creates cool, mysterious, nocturnal mood.",
  "COLOR TEMPERATURE MIX — WARM AND COOL LIGHTS combined; creates visual interest and depth through color contrast.",
  "COLORED GEL — LIGHT FILTERED through colored material; adds creative color tint and artistic mood.",
  "CONTINUOUS LED — CONSTANT BRIGHT LIGHT with adjustable color; modern, controlled illumination with accurate colors.",
  "CONTRE-JOUR — SHOOTING INTO LIGHT SOURCE with glowing edges; creates ethereal halo effect and atmospheric flare.",
  "CROSS LIGHTING — LIGHTS FROM OPPOSITE SIDES balancing; creates dimensional, sculptural quality.",
  "CYBERPUNK LIGHTING — MIXED NEON COLORS pink and cyan; creates futuristic, dystopian aesthetic with color contrast.",
  "DAPPLED FOREST LIGHT — SUNLIGHT THROUGH LEAVES creating spotted patterns; adds organic texture and natural depth.",
  "EDGE LIGHTING — BRIGHT RIM LIGHT separating subject from background; creates glowing outline and dramatic separation.",
  "FIRE LIGHT — WARM FLICKERING GLOW from flames; adds primal, dynamic, warm atmosphere.",
  "FLAT LIGHTING — EVEN FRONTAL ILLUMINATION with minimal shadows; creates clean, commercial, straightforward look.",
  "GOLDEN HOUR WARM — SOFT SUNSET LIGHT from low angle; creates warm amber glow with long shadows and romantic atmosphere.",
  "GRADIENT LIGHTING — SMOOTH LIGHT TRANSITION across scene; creates dimensional depth and visual interest.",
  "GRID SPOT — FOCUSED BEAM with precise control; creates dramatic highlight on specific area.",
  "HARD LIGHT — SMALL, FOCUSED LIGHT SOURCE with defined shadows; creates texture emphasis and dramatic mood.",
  "HARSH NOON SUN — DIRECT OVERHEAD SUNLIGHT with strong shadows; creates dramatic contrast and intense highlights.",
  "HIGH KEY BRIGHT — SOFT, BRIGHT, MINIMAL SHADOWS; creates airy, positive, clean aesthetic with light tones.",
  "LENS FLARE ARTISTIC — BRIGHT LIGHT SOURCE creating optical artifacts; adds cinematic quality and dreamy atmosphere.",
  "LOOP LIGHTING — SLIGHT SHADOW LOOP from nose; flattering portrait lighting with natural dimension.",
  "LOW KEY DRAMATIC — MOSTLY SHADOWS with selective highlights; creates moody, dramatic, mysterious atmosphere.",
  "MOTIVATED LIGHTING — LIGHT FROM LOGICAL SOURCE within scene; creates believable, natural illumination.",
  "NEGATIVE FILL — LIGHT ACTIVELY BLOCKED to deepen shadows; creates dramatic contrast and sculpted form.",
  "NEON GLOW — VIBRANT COLORED LIGHT from neon signs; adds electric energy and urban night atmosphere.",
  "OVERCAST DIFFUSED — SOFT CLOUDY SKY LIGHT with no harsh shadows; creates even, flattering illumination with subtle contrast.",
  "PRACTICAL LIGHTS — VISIBLE LIGHT SOURCES in scene (lamps, screens); adds realism and motivated lighting.",
  "PULSING LIGHTS — RHYTHMIC LIGHT CHANGES; adds energy, movement, and dynamic quality.",
  "REMBRANDT LIGHTING — TRIANGULAR CHEEK HIGHLIGHT with dramatic side lighting; classic portrait setup with depth and dimension.",
  "RING LIGHT — CIRCULAR LIGHT AROUND LENS with even illumination; creates distinctive catch lights and shadow-free beauty lighting.",
  "SOFT LIGHT — LARGE, DIFFUSED LIGHT SOURCE with gentle shadows; creates flattering, smooth illumination.",
  "SPLIT LIGHTING — HALF FACE ILLUMINATED, half in shadow; creates dramatic divide and mysterious mood.",
  "SPOTLIGHT DRAMATIC — FOCUSED BEAM in darkness; creates theatrical, isolated, dramatic effect.",
  "STADIUM LIGHTS — MULTIPLE BRIGHT SOURCES overhead; creates sports arena, high-energy atmosphere.",
  "STREET LAMP GLOW — WARM AMBER LIGHT from above; creates urban night, nostalgic atmosphere.",
  "STROBE MOTION — MULTIPLE FLASHES capturing movement; creates energetic, dynamic, frozen-motion effect.",
  "STUDIO FLASH — CRISP, BRIGHT STROBE LIGHT; creates sharp, clean, professional look with frozen motion.",
  "SUNBEAM RAYS — VISIBLE LIGHT SHAFTS through opening; creates spiritual, dramatic, uplifting quality.",
  "SUNSET RIM LIGHT — WARM BACKLIGHT from setting sun; creates golden outline and magical hour glow.",
  "THREE-POINT LIGHTING — KEY, FILL, AND BACK LIGHT balanced; professional studio setup with controlled dimension.",
  "TOP LIGHTING — LIGHT FROM DIRECTLY ABOVE; creates dramatic downward shadows and mysterious mood.",
  "UNDER LIGHTING — LIGHT FROM BELOW; creates eerie, horror-style, unnatural effect.",
  "VOLUMETRIC FOG — VISIBLE LIGHT BEAMS through mist or smoke; adds depth and atmospheric drama.",
  "WARM CANDLELIGHT — FLICKERING ORANGE GLOW from flame; intimate, romantic atmosphere with warm color temperature.",
  "WINDOW LIGHT NATURAL — SOFT DIRECTIONAL LIGHT from window; creates natural, flattering illumination with gradual falloff.",
] as const;
