/**
 * Weather variation prompts for image generation.
 *
 * Includes diverse weather conditions and atmospheric phenomena
 * that affect the mood and visual appearance of scenes.
 * Ordered to provide maximum variety in atmospheric conditions.
 */
export const WEATHER_VARIATIONS = [
  "AFTERNOON HEAT — PEAK SUNLIGHT intensity; creates harsh overhead lighting, minimal shadows, hot atmosphere with heat shimmer.",
  "ASH FALL — VOLCANIC ASH falling from sky; creates apocalyptic atmosphere, gray particles in air, coating surfaces.",
  "AURORAS — NORTHERN/SOUTHERN LIGHTS visible; creates ethereal green and purple light dancing in night sky, magical atmosphere.",
  "AUTUMN MIST — COOL SEASON FOG; creates atmospheric fall morning with mist, falling leaves, and transitional season mood.",
  "BREEZY — LIGHT WIND with gentle movement; adds subtle motion to environment, slight ripple effects, and fresh atmosphere.",
  "CALM — STILL AIR with no wind; creates serene, peaceful atmosphere with no environmental movement.",
  "CLEAR SKY — BRIGHT SUNLIGHT with no cloud cover; creates sharp shadows, vibrant colors, and high contrast.",
  "CLOUDBURST — SUDDEN HEAVY RAIN from cloud; creates dramatic weather shift, intense rainfall, and dynamic atmospheric event.",
  "CLOUDY — COMPLETE CLOUD COVER without precipitation; creates flat, diffused lighting with gray sky and soft shadows.",
  "COLD SNAP — EXTREME COLD visible effects; creates icy breath vapor, frost formations, and harsh winter atmosphere.",
  "CRISP — COLD CLEAR AIR; creates sharp details, bright colors, and invigorating fresh atmosphere typical of autumn/winter.",
  "DOUBLE RAINBOW — TWO RAINBOWS visible simultaneously; creates rare, magical atmospheric phenomenon with vibrant colors.",
  "DRIZZLE — FINE MIST RAIN barely visible; creates atmospheric moisture, slight dampness on surfaces, and soft diffused light.",
  "DRY — LOW HUMIDITY conditions; creates crisp, clear atmosphere with sharp details and high contrast.",
  "DUST STORM — AIRBORNE DUST reducing visibility; creates desert atmosphere, warm tones, and dramatic environmental effect.",
  "FOG — DENSE MIST reducing visibility; creates mysterious atmosphere, muted colors, and depth through layers of fog.",
  "FREEZING FOG — SUPERCOOLED FOG DROPLETS; creates rime ice on surfaces, hazardous conditions, winter atmosphere with fog.",
  "FROST — ICE CRYSTALS coating surfaces; creates sparkling crystalline texture on objects, cold atmosphere, and winter detailing.",
  "GLOOMY — DARK HEAVY CLOUDS without rain; creates depressive atmosphere, low light, and ominous pre-storm mood.",
  "GROUND FOG — LOW-LYING MIST near surface; creates ankle to knee-high fog layer, ethereal ground effect, with clear air above.",
  "HAIL — ICE PELLETS FALLING from sky; creates intense weather event with visible ice particles and dramatic impact.",
  "HAZE — ATMOSPHERIC PARTICLES reducing clarity; creates soft-focus effect, reduced contrast, and dreamy distant views.",
  "HEAT WAVE — VISIBLE HEAT DISTORTION in air; creates shimmering heat lines, intense sunlight, and oppressive hot atmosphere.",
  "HEAVY RAIN — INTENSE DOWNPOUR with strong precipitation; creates dramatic weather effect, reduced visibility, and heavy water streaks.",
  "HEAVY SNOW — INTENSE SNOWFALL with reduced visibility; creates blizzard-like conditions, white-out effect, and dramatic winter scene.",
  "HUMID — HIGH MOISTURE in atmosphere; creates slight haze, visible heat shimmer, and sultry tropical feeling.",
  "HURRICANE — EXTREME WIND AND RAIN; creates catastrophic weather with horizontal rain, debris, and intense storm effects.",
  "ICE STORM — FREEZING RAIN coating surfaces; creates glass-like ice layer on everything, treacherous conditions, crystalline beauty.",
  "INDIAN SUMMER — WARM AUTUMN DAYS; creates pleasant warm weather in fall season, golden light, and comfortable atmosphere.",
  "LIGHT FOG — THIN MIST with moderate visibility; adds atmospheric depth and dreamy quality while maintaining scene clarity.",
  "LIGHT RAIN — GENTLE RAINFALL with visible droplets; creates wet surfaces, subtle reflections, and a soft atmospheric haze.",
  "LIGHT SNOW — GENTLE SNOWFALL with sparse flakes; adds winter ambiance while maintaining visibility and scene detail.",
  "MARINE LAYER — COASTAL FOG from ocean; creates thick morning fog near coast, cool maritime atmosphere, gradual clearing.",
  "MIST — FINE WATER DROPLETS suspended in air; creates ethereal, soft-focus effect with subtle atmospheric haze.",
  "MOONLIT — NIGHTTIME ILLUMINATION from moon; creates cool blue tones, deep shadows, and mysterious nocturnal atmosphere.",
  "MORNING DEW — WATER DROPLETS on surfaces; creates glistening beads on grass and objects, fresh morning atmosphere, sparkle effect.",
  "MOSTLY SUNNY — MINIMAL CLOUDS with dominant sunshine; creates bright, cheerful atmosphere with occasional cloud interest.",
  "MUGGY — WARM HUMID CONDITIONS; creates uncomfortable atmosphere, visible moisture, tropical heat feeling.",
  "OVERCAST — THICK CLOUD COVER diffusing sunlight; creates soft, even lighting with minimal shadows and muted colors.",
  "PARTLY CLOUDY — SCATTERED CLOUDS with intermittent sun; creates dynamic lighting with shifting shadows and patches of bright light.",
  "PARTLY SUNNY — CLOUDS WITH SUN BREAKS; creates dynamic sky with dramatic cloud formations and shafts of sunlight.",
  "PATCHY FOG — FOG IN SCATTERED AREAS; creates varied visibility with fog banks and clear patches, mysterious selective coverage.",
  "RAINBOW — VISIBLE SPECTRUM after rain; creates colorful arc in sky, hopeful atmosphere, and dramatic weather clearing.",
  "SANDSTORM — INTENSE WIND-BLOWN SAND; creates harsh desert conditions, reduced visibility, and dramatic swirling particles.",
  "SLEET — MIXED RAIN AND ICE falling; creates transitional weather with both water and ice elements visible.",
  "SMOG — POLLUTED AIR with reduced visibility; creates urban atmospheric haze, muted colors, and environmental concern atmosphere.",
  "SNOW FALLING — ACTIVE SNOWFALL with visible flakes; creates winter atmosphere, accumulation on surfaces, and soft white particles in air.",
  "SNOWSTORM — BLIZZARD CONDITIONS with strong winds; creates harsh winter weather, blowing snow, and dramatic atmospheric effect.",
  "SPRING SHOWER — BRIEF LIGHT RAIN; creates fresh, cleansing rain with quick passage, renewal atmosphere, and nature awakening.",
  "STARRY NIGHT — CLEAR NIGHT SKY with visible stars; creates cosmic background, dark atmosphere, and sense of vastness.",
  "SUMMER HAZE — WARM HUMID ATMOSPHERE; creates soft focus distance, heat shimmer, and lazy summer afternoon feeling.",
  "SUN SHOWER — RAIN WHILE SUN SHINES; creates unique lighting with both rain and sunshine, rainbow potential, mixed atmosphere.",
  "SUNRISE CLEAR — GOLDEN HOUR MORNING light with clear sky; creates warm tones, long shadows, and optimistic beginning mood.",
  "SUNRISE CLOUDY — MORNING LIGHT filtered through clouds; creates soft, diffused sunrise with muted warm tones and gentle lighting.",
  "SUNSET CLEAR — GOLDEN HOUR EVENING light with clear sky; creates warm amber glow, romantic atmosphere, and golden tones.",
  "SUNSET CLOUDY — EVENING LIGHT through cloud cover; creates dramatic sky with varied colors, soft light, and atmospheric depth.",
  "THUNDERSTORM — DARK STORM CLOUDS with lightning; creates dramatic contrast, ominous atmosphere, and intense weather energy.",
  "TORNADO — ROTATING FUNNEL CLOUD visible; creates dramatic, dangerous weather event with extreme atmospheric conditions.",
  "TWILIGHT — TRANSITION BETWEEN DAY/NIGHT; creates blue hour lighting, soft ambient glow, and atmospheric in-between time.",
  "WILDFIRE SMOKE — SMOKE HAZE from distant fires; creates orange/red atmospheric tinting, hazy sun, and eerie atmospheric effect.",
  "WINDY — STRONG WINDS affecting environment; creates movement in vegetation, clothing, and loose objects, dynamic atmosphere.",
  "WINTER SUN — BRIGHT COLD DAY; creates brilliant sunlight with cold air, crisp shadows, sparkling snow or frost.",
] as const;
